# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.ingredient:
        class: AppBundle\Admin\IngredientAdmin
        arguments: [~, AppBundle\Entity\Ingredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Інгредієнти, group: Pizza-Builder }

    admin.preset:
        class: AppBundle\Admin\PresetAdmin
        arguments: [~, AppBundle\Entity\Preset, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Готові піцци, group: Pizza-Builder }

    admin.order:
            class: AppBundle\Admin\OrderAdmin
            arguments: [~, AppBundle\Entity\Order, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Замовлення, group: Pizza-Builder }
